// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_temy1wPOzJFEqsZlBZHwJbmioZk_89U',
    appId: '1:489957335274:web:c20a4cb562f653e7fdf793',
    messagingSenderId: '489957335274',
    projectId: 'programming-a4595',
    authDomain: 'programming-a4595.firebaseapp.com',
    storageBucket: 'programming-a4595.firebasestorage.app',
    measurementId: 'G-P9G0X51VRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK4HDlL-5mb8nA9X_9U6VULr0GVvBAXpE',
    appId: '1:489957335274:android:942bacc6a03f80fbfdf793',
    messagingSenderId: '489957335274',
    projectId: 'programming-a4595',
    storageBucket: 'programming-a4595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3PfnB6QsVAMKCouNra4sxcJ67_RtiMHE',
    appId: '1:489957335274:ios:42ba59d3ecf7b34cfdf793',
    messagingSenderId: '489957335274',
    projectId: 'programming-a4595',
    storageBucket: 'programming-a4595.firebasestorage.app',
    iosBundleId: 'com.example.programmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3PfnB6QsVAMKCouNra4sxcJ67_RtiMHE',
    appId: '1:489957335274:ios:42ba59d3ecf7b34cfdf793',
    messagingSenderId: '489957335274',
    projectId: 'programming-a4595',
    storageBucket: 'programming-a4595.firebasestorage.app',
    iosBundleId: 'com.example.programmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_temy1wPOzJFEqsZlBZHwJbmioZk_89U',
    appId: '1:489957335274:web:86b259b440092542fdf793',
    messagingSenderId: '489957335274',
    projectId: 'programming-a4595',
    authDomain: 'programming-a4595.firebaseapp.com',
    storageBucket: 'programming-a4595.firebasestorage.app',
    measurementId: 'G-CJDLNS2JL5',
  );
}
